### ISSUE TITLE
Module does not work anymore

### ISSUE THREAD

**Issue by frnjjq** [EdgarVaguencia/node-ivoox#2]
Hi mate I have tried to use this module but it does not longer work properly.
In this line
 -> var title = cheerio(i).find('div.content h4 a');

It is not returning correctly the title. iVoox must have changed something around, I am not really great an jQuery so I could not solve by myself.

**Comment by EdgarVaguencia** [comment]
The ivoox design has changed 😫

**Comment by frnjjq** [comment]
I just wanted you know. I understand you might not want to spend time on it ;). I tried to fit it myself so I could pull request you, but I am quite bad at web programming.

**Comment by EdgarVaguencia** [comment]
Yes thanks.

New version is ready 206f327a7a63c82508d64991bc3aaae870c4f287
